// Purpose: Tailwind CSS + DaisyUI configuration with custom sakura/kintsukuroi themes.
import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: [
          "'Plus Jakarta Sans'",
          'Inter',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'sans-serif',
        ],
        body: [
          "'Plus Jakarta Sans'",
          'Inter',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'sans-serif',
        ],
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        sakura: {
          'primary': '#1f5c2e',
          'primary-content': '#f7fcf7',
          'secondary': '#3d7a4a',
          'secondary-content': '#0a1309',
          'accent': '#1f5c2e',
          'accent-content': '#f7fcf7',
          'neutral': '#0a1309',
          'neutral-content': '#edf3ec',
          'base-100': '#edf3ec',
          'base-200': '#e0ebe0',
          'base-300': '#d1e0d1',
          'base-content': '#0a1309',
          'info': '#3b82f6',
          'success': '#22c55e',
          'warning': '#f59e0b',
          'error': '#ef4444',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '1.9rem',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.95',
        },
      },
      {
        kintsukuroi: {
          'primary': '#c9a84c',
          'primary-content': '#1a1714',
          'secondary': '#a08a3e',
          'secondary-content': '#e8e0d4',
          'accent': '#c9a84c',
          'accent-content': '#1a1714',
          'neutral': '#e8e0d4',
          'neutral-content': '#1a1714',
          'base-100': '#1a1714',
          'base-200': '#242019',
          'base-300': '#2e2a23',
          'base-content': '#e8e0d4',
          'info': '#3b82f6',
          'success': '#22c55e',
          'warning': '#f59e0b',
          'error': '#ef4444',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '1.9rem',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.95',
        },
      },
    ],
    darkTheme: false,
    base: true,
    styled: true,
    utils: true,
    logs: true,
    themeRoot: ':root',
  },
} satisfies Config
